### ISSUE TITLE
cerner_splunk_forwarder_monitors fails when passed empty monitor list

### ISSUE THREAD

**Issue by tboettch** [cerner/cerner_splunk#85]
I get the error below when passing an empty list of monitors to ```cerner_splunk_forwarder_monitors```. Initial debugging suggests that an empty hash is passed to Chef's ```file.contents```, which is not permitted. The empty hash seems to be generated by ```CernerSplunk::LWRP.convert_monitors``` because there are no monitors to fold over.

My desired behavior is that any existing monitors be removed in this case, as if delete had been specified.

I have a proposed fix that I will submit shortly.

**Comment by tboettch** [comment]
I forgot to attach the stacktrace, here it is:

```Generated at 2015-09-02 10:39:41 -0500
Chef::Exceptions::ValidationFailed: cloud_infra_tomcat_platform[foobar] (cloud_infra_tomcat_platform::test_main line 24) had an error: Chef::Exceptions::ValidationFailed: splunk_app[foobar] (/tmp/kitchen/cookbooks/cerner_splunk/providers/forwarder_monitors.rb line 11) had an error: Chef::Exceptions::ValidationFailed: Option content must be a kind of String!  You passed {}.
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:157:in `_pv_kind_of'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:70:in `block (2 levels) in validate'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:67:in `each'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:67:in `block in validate'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:57:in `each'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:57:in `validate'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:97:in `set_or_return'
/opt/chef/embedded/apps/chef/lib/chef/resource/file.rb:59:in `content'
/tmp/kitchen/cookbooks/cerner_splunk/libraries/splunk_app.rb:288:in `manage_file'
/tmp/kitchen/cookbooks/cerner_splunk/libraries/splunk_app.rb:149:in `block in action_create'
/tmp/kitchen/cookbooks/cerner_splunk/libraries/splunk_app.rb:142:in `each'
/tmp/kitchen/cookbooks/cerner_splunk/libraries/splunk_app.rb:142:in `action_create'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:121:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:648:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:125:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:648:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:431:in `do_run'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:207:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:207:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:226:in `block in run_application'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:218:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:218:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:55:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:38:in `load'
/usr/bin/chef-solo:38:in `<main>'
```
