### ISSUE TITLE
Chef Client 12.5.1 issues with  splunk_forwarder_monitors provider

### ISSUE THREAD

**Issue by maximusfloydus** [cerner/cerner_splunk#94]
When upgrading from Chef client 12.4.3 -> 12.5.1 I started to get failures configuring my splunk forwarder monitors (errors below).  Please let me know if there is a change need in this cookbook or how I am using to resolve this issue.

```
splunk_forwarder_monitors[my_service] action install[2015-10-09T12:36:40-05:00] WARN: Using an LWRP provider by its name (CernerSplunkForwarderMonitors) directly is no longer supported in Chef 12 and will be removed. Use Chef::ProviderResolver.new(node, resource, action) instead.
[2015-10-09T12:36:40-05:00] WARN: Class Chef::Provider::CernerSplunkForwarderMonitors does not declare 'resource_name :cerner_splunk_forwarder_monitors'.
[2015-10-09T12:36:40-05:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
 (up to date)
splunk_app[my_service] action create[2015-10-09T12:36:40-05:00] WARN: Class Chef::Provider::SplunkApp does not declare 'resource_name :splunk_app'.
[2015-10-09T12:36:40-05:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
```

```
splunk_forwarder_monitors[my_service] action install  
==============================================================================  
Error executing action `install` on resource 'splunk_forwarder_monitors[my_service]'  
===============================================================================
    Chef::Exceptions::ProviderNotFound  
    ----------------------------------  
    Cannot find a provider for splunk_forwarder_monitors[my_service] on redhat version 6.6
```

**Comment by acharlieh** [comment]
@maximusfloydus Did you change from the Chef 10 era Cerner internal only splunk_forwarder cookbook to the cerner_splunk cookbook at the same time? `splunk_forwarder_monitors` was an LWRP that was in the splunk_forwarder cookbook, the same LWRP for this cookbook is named `cerner_splunk_forwarder_monitors` (The beginning of the LWRP name in the past had to be the source cookbook name, although I believe with some of the changes that have been made since that point we might be able to get the new LWRP to use both names)

**Comment by nimeshsubramanian** [comment]
I have attached the error that I get when i converged the f_default vagrant box; It looks like chef for some reason is looking for splunk_forwarder_monitors!. Further investigation is needed into this since with the 12.5 release chef has basically reworked the way LWRP/HWRP(https://www.chef.io/blog/2015/10/08/chef-client-12-5-released/) are written :( 
```
==> f_default: * splunk_forwarder_monitors[foo] action install
==> f_default:       
==> f_default: 
==> f_default:       
==> f_default: ================================================================================
==> f_default:       
==> f_default: Error executing action `install` on resource 'splunk_forwarder_monitors[foo]'
==> f_default:       
==> f_default: ================================================================================
==> f_default:       
==> f_default: 
==> f_default: 
==> f_default:       
==> f_default: Chef::Exceptions::ProviderNotFound
==> f_default:       
==> f_default: ----------------------------------
==> f_default:       
==> f_default: Cannot find a provider for splunk_forwarder_monitors[foo] on centos version 6.7
==> f_default:       
==> f_default: 
==> f_default: 
==> f_default:       
==> f_default: Resource Declaration:
==> f_default:       
==> f_default: ---------------------
==> f_default:       
==> f_default: # In /var/chef/cache/cookbooks/cerner_splunk_test/providers/lwrp.rb
==> f_default: 
==> f_default:       
==> f_default: 
==> f_default: 
==> f_default:       
==> f_default:   4:   cerner_splunk_forwarder_monitors new_resource.name do
==> f_default: 
==> f_default:       
==> f_default:   5:     app new_resource.app
==> f_default: 
==> f_default:       
==> f_default:   6:     index new_resource.index
==> f_default: 
==> f_default:       
==> f_default:   7:     monitors new_resource.monitors
==> f_default: 
==> f_default:       
==> f_default:   8:   end
==> f_default: 
==> f_default:         9: end
==> f_default:       
==> f_default:       
==> f_default: Compiled Resource:
==> f_default: 
==> f_default:       ------------------
==> f_default:       
==> f_default: # Declared in /var/chef/cache/cookbooks/cerner_splunk_test/providers/lwrp.rb:4:in `block in class_from_file'
==> f_default: 
==> f_default:       
==> f_default: 
==> f_default:       splunk_forwarder_monitors("foo") do
==> f_default:         action :install
==> f_default:         retries 0
==> f_default:         retry_delay 2
==> f_default:         default_guard_interpreter :default
==> f_default:         index "pop_health"
==> f_default:         declared_type :cerner_splunk_forwarder_monitors
==> f_default:         cookbook_name "cerner_splunk_test"
==> f_default:         app "foo"
==> f_default:       
==> f_default:   monitors [{:path=>"/testlogs/one/*.log", :sourcetype=>"access_combined"}, {:path=>"/testlogs/two/access1.log", :sourcetype=>"access_combined", :index=>"bobs_index_emporium"}]
==> f_default: 
==> f_default:       
==> f_default: end
==> f_default:       
==> f_default: 
==> f_default: [2015-10-13T19:09:49+00:00] INFO: Running queued delayed notifications before re-raising exception
==> f_default:     
==> f_default: 
==> f_default:     
==> f_default: ================================================================================
==> f_default:     
==> f_default: Error executing action `go` on resource 'cerner_splunk_test_lwrp[foo]'
==> f_default:     
==> f_default: ================================================================================
==> f_default:     
==> f_default: 
==> f_default: 
==> f_default:     
==> f_default: Chef::Exceptions::ProviderNotFound
==> f_default:     
==> f_default: ----------------------------------
==> f_default:     
==> f_default: splunk_forwarder_monitors[foo] (/var/chef/cache/cookbooks/cerner_splunk_test/providers/lwrp.rb line 4) had an error: Chef::Exceptions::ProviderNotFound: Cannot find a provider for splunk_forwarder_monitors[foo] on centos version 6.7
==> f_default:     
==> f_default: 
==> f_default: 
==> f_default:     
==> f_default: Resource Declaration:
==> f_default:     
==> f_default: ---------------------
==> f_default:     
==> f_default: # In /var/chef/cache/cookbooks/cerner_splunk_test/recipes/default.rb
==> f_default: 
==> f_default:     
==> f_default:      31: cerner_splunk_test_lwrp 'foo' do
==> f_default:      32:   index 'pop_health'
==> f_default:     
==> f_default:  33:   monitors [{
==> f_default:      34:     path: '/testlogs/one/*.log',
==> f_default:      35:     sourcetype: 'access_combined'
==> f_default:      36:   }, {
==> f_default:      37:     path: '/testlogs/two/access1.log',
==> f_default:      38:     sourcetype: 'access_combined',
==> f_default: 
==> f_default:      39:     index: 'bobs_index_emporium'
==> f_default:      40:   }]
==> f_default:      41: end
==> f_default:      42: 
==> f_default: 
==> f_default:     
==> f_default: 
==> f_default: 
==> f_default:     
==> f_default: Compiled Resource:
==> f_default:     
==> f_default: ------------------
==> f_default: 
==> f_default:     # Declared in /var/chef/cache/cookbooks/cerner_splunk_test/recipes/default.rb:31:in `from_file'
==> f_default:     
==> f_default:     
==> f_default: cerner_splunk_test_lwrp("foo") do
==> f_default:       action [:go]
==> f_default:       retries 0
==> f_default:       retry_delay 2
==> f_default:       default_guard_interpreter :default
==> f_default:       declared_type :cerner_splunk_test_lwrp
==> f_default:       cookbook_name "cerner_splunk_test"
==> f_default:       recipe_name "default"
==> f_default:       index "pop_health"
==> f_default:       monitors [{:path=>"/testlogs/one/*.log", :sourcetype=>"access_combined"}, {:path=>"/testlogs/two/access1.log", :sourcetype=>"access_combined", :index=>"bobs_index_emporium"}]
==> f_default:       app "foo"
==> f_default:     end
==> f_default:     
==> f_default: 
==> f_default: 
==> f_default: [2015-10-13T19:09:49+00:00] INFO: Running queued delayed notifications before re-raising exception
==> f_default: [2015-10-13T19:09:49+00:00] INFO: ruby_block[splunk-delayed-restart] sending restart action to service[splunk] (delayed)
==> f_default: Recipe: cerner_splunk::_install
==> f_default:   
==> f_default: * service[splunk] action restart
==> f_default:  (skipped due to only_if)
==> f_default: 
==> f_default: Running handlers:
==> f_default: [2015-10-13T19:09:49+00:00] ERROR: Running exception handlers
==> f_default: Running handlers complete
==> f_default: 
==> f_default: [2015-10-13T19:09:49+00:00] ERROR: Exception handlers complete
==> f_default: Chef Client failed. 64 resources updated in 03 minutes 23 seconds
==> f_default: [2015-10-13T19:09:49+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> f_default: [2015-10-13T19:09:49+00:00] ERROR: cerner_splunk_test_lwrp[foo] (cerner_splunk_test::default line 31) had an error: Chef::Exceptions::ProviderNotFound: splunk_forwarder_monitors[foo] (/var/chef/cache/cookbooks/cerner_splunk_test/providers/lwrp.rb line 4) had an error: Chef::Exceptions::ProviderNotFound: Cannot find a provider for splunk_forwarder_monitors[foo] on centos version 6.7
==> f_default: [2015-10-13T19:10:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
MAC1335458:cerner_splunk ns028372$ vagrant destroy
```
*note:*
I had to change the shell provision command for the chef box here: https://github.com/cerner/cerner_splunk/blob/stable/Vagrantfile#L82 to 
```yum install -y https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chefdk-0.9.0-1.el6.x86_64.rpm``` 
I made the change only as a temp workaround as cert for chef.sh had expired.

**Comment by acharlieh** [comment]
Sigh... I'm an idiot... apparently this line that never worked before, started "working": https://github.com/cerner/cerner_splunk/blame/stable/resources/forwarder_monitors.rb#L16

**Comment by aaronblythe** [comment]
May be relevant https://www.chef.io/blog/2015/10/08/chef-client-12-5-released/ seems lwrp is deprecated... However shouldn't be removed. Maybe there is possibly a non-passive change in Chef?

**Comment by acharlieh** [comment]
Unrelated note, with help from @OBrienCommaJosh we got the certificate updated for https://chef.sh so the workaround to get Vagrant to work by @nimeshsubramanian is no longer needed.

**Comment by acharlieh** [comment]
Going to work this together with #70 but they're not really duplicates it seems, also we should be able to give people the ability to use the old resource name or the new resource name now. 
https://github.com/acharlieh/cerner_splunk/commit/3e39177b5ddaecd0bc3d5255e79068ad89c073da

Apparently provides (needed to solve 70) isn't present in 11.6 however, so need a bit more hacking on this >_<

**Comment by maximusfloydus** [comment]
@acharlieh - What is the best way I can help you verify your fix?  Should I point my berksfile to your repo?
